package com.woop.Squad4J.event;

/**
 * @author Robert Engle
 * <p>
 * A class descibing the types of events that can occur from either the log file, RCON console, or A2S queries.
 */
public enum EventType {
    //Log file
    ADMIN_BROADCAST, DEPLOYABLE_DAMAGED, NEW_GAME, PLAYER_CONNECTED, PLAYER_DAMAGED, PLAYER_DIED, PLAYER_DISCONNECTED,
    PLAYER_POSSESS, PLAYER_UNPOSSESS, PLAYER_REVIVED, PLAYER_WOUNDED, ROUND_WINNER, SERVER_TICK_RATE, SQUAD_CREATED,
    STEAMID_CONNECTED,

    //RCON
    CHAT_MESSAGE, PLAYER_BANNED, PLAYER_WARNED, PLAYER_KICKED, ENTERED_IN_ADMIN_CAM, LEFT_FROM_ADMIN_CAM, PLAYERLIST_UPDATED,
    SQUADLIST_UPDATED, LAYERINFO_UPDATED,

    //A2S
    A2S_UPDATED
}
